name: windows

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: install deploy-dll
      run: cargo install --path .
    - name: Test
      run: |
        vcpkg install libzip --triplet=x64-windows
        mkdir test
        cp C:/vcpkg/installed/x64-windows/bin/zip.dll ./test
        ls -l ./test
        deploy-dll ./test/zip.dll --cmake-prefix-path=C:/vcpkg/installed/x64-windows --verbose

    - name: Make package
      run: |
        cargo build --release
        mkdir target/make-package
        cargo install --path . --root target/make-package
        cp C:/mingw/bin/objdump.exe ./target/make-package/bin
        deploy-dll ./target/make-package/bin/deploy-dll.exe --shallow-search-dir=C:/mingw/bin
        deploy-dll ./target/make-package/bin/objdump.exe --shallow-search-dir=C:/mingw/bin

    - name: Upload package
      uses: actions/upload-artifact@v3
      with:
        name: SharedLibDeployer-1.0.0-win64
        path: target/make-package
        if-no-files-found: error
